//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JobSearch.MVCWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class InterviewStatus
    {
        public InterviewStatus()
        {
            this.InterviewLog = new HashSet<InterviewLog>();
        }
    
        public byte InterviewStatusId { get; set; }
        public string InterviewStatusDescription { get; set; }
    
        public virtual ICollection<InterviewLog> InterviewLog { get; set; }
    }
}
