//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JobSearch.MVCWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class InterviewLog
    {
        public int InterviewId { get; set; }
        public long ClientCompanyId { get; set; }
        public long RecruiterCompanyId { get; set; }
        public int JobId { get; set; }
        public byte InterviewStatusId { get; set; }
        public System.DateTime InterviewDate { get; set; }
        public string InterviewTime { get; set; }
        public string Notes { get; set; }
    
        public virtual InterviewStatus InterviewStatus { get; set; }
        public virtual Job Job { get; set; }
    }
}
