//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JobSearch.MVCWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Job
    {
        public Job()
        {
            this.InterviewLog = new HashSet<InterviewLog>();
        }
    
        public int JobId { get; set; }
        public string JobTitle { get; set; }
        public string JobDescription { get; set; }
        public long CompanyId { get; set; }
        public byte JobStatusId { get; set; }
    
        public virtual Company Company { get; set; }
        public virtual ICollection<InterviewLog> InterviewLog { get; set; }
        public virtual JobStatus JobStatus { get; set; }
    }
}
